### ISSUE TITLE
A issue in validate_and_count.py

### ISSUE THREAD

**Issue by TequilaSunrise84** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#1]
https://github.com/FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022/blob/d72ffa3efbc5dd67d8697ce84611020fe316fa8b/10X_Visium_samples/validate_and_count.py#L13
 I just run the code in **validate_and_count.py**
I'm not sure which file is "metadata_file", I notice that the path of "metadata_file" is `metadata_file = 'data_processing/selected_samples_for_counting/sample.visium_D1_metadata.csv'`, but the path and the file didn't appear in the previous analysis... I would like to know how to find this file.
I would appreciate your help.

**Comment by hanruiw** [comment]
Hi, metadata file is the metadata of a Seurat object. Please let me know if you have any questions!

**Comment by hanruiw** [comment]
1.

**Comment by hanruiw** [comment]
Hi, metadata file is the metadata of a Seurat object. Please let me know if you have any questions!

**Comment by TequilaSunrise84** [comment]
Hello,
Thanks for your reply. I tried to use the metadata file extracted from `sample.filtered_matrix@meta.data` in Visium.R. But I still meet problem in process of extracting the Bacteria Positive cells. It seems that the code `int(each_line_list[position])` has some problems. 
So I would like to check with you whether the "metadata_file" is correct and whether subsequent changes to this file are required.
Thanks you very much !

**Comment by hanruiw** [comment]
Hi, sorry for the late response, the "metadata_file" is written using `write.csv(sample.visium_metadata,sample.visium_metadata_filename, quote = FALSE,row.names = TRUE)`
and looks like this: 
![图片](https://user-images.githubusercontent.com/61566114/212149913-303d7669-910e-4a74-a40d-3153393fbab0.png)

**Comment by TequilaSunrise84** [comment]
Thanks you for your reply ! I will try it again !

**Comment by hanruiw** [comment]
Hi,  sorry for confusion, I updated the pipeline code and sample names in visium output, could you please try again using the updated output files?

**Comment by TequilaSunrise84** [comment]
Hello, I have tried the pipeline code again with new output file and successfully run the code, thanks you for your help !
