### ISSUE TITLE
pathseq bam is missing reads  in the literature

### ISSUE THREAD

**Issue by jr-ran** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#10]
In the CRC 16 sample results, the bam results I obtained for pathseq did not contain the reads in the literature, e.g AAACACCAATAACTGC-1+TAGCGGGATGTT

`$ samtools view 01.Pathseq/CRC_16.output.pathseq.bam|egrep "VH00699:3:AAAHK77HV:1:2105:49816:8308"`

**Comment by hanruiw** [comment]
Hi,

Thank you for your interest in our paper! In order to be annotated as a bacteria read, a read has to contain valid `UB` and `CB` tags from Cellranger as well as `YP` tag from PathSeq. Would you mind share more details about your question and the result for `$ samtools view 01.Pathseq/CRC_16.output.pathseq.bam|egrep "VH00699:3:AAAHK77HV:1:2105:49816:8308"`?

Best regards,
Hanrui

**Comment by jr-ran** [comment]
Dear Hanrui,
My reference genome is download from pathseqDB, and gatk command is 
`gatk-4.1.3.0/gatk \
 --java-options -Xmx100G \
 PathSeqPipelineSpark \
    --input ${dir}/CRC_16/outs/possorted_genome_bam.bam \
    --filter-bwa-image ${refdir}/host/pathseq_host.fa.img \
    --kmer-file ${refdir}/host/pathseq_host.bfi \
    --min-clipped-read-length 60 \
    --microbe-fasta ${refdir}/micro/pathseq_microbe.fa \
    --microbe-bwa-image ${refdir}/micro/pathseq_microbe.fa.img \
    --taxonomy-file ${refdir}/micro/pathseq_taxonomy.db \
    --output ${odir}/01.Pathseq/CRC_16.output.pathseq.bam \
    --scores-output ${odir}/01.Pathseq/CRC_16.output.pathseq.csv
    --is-host-aligned false \
    --filter-duplicates false \
    --min-score-identity .7`
Bam results as input were analyzed using umi_annotater.py.
`each_sample=CRC_16
python UMI_annotator.py ${bam_path}/${each_sample}/outs/possorted_genome_bam.bam \
'' \
${bam_path}/${each_sample}/outs/raw_feature_bc_matrix/barcodes.tsv.gz \
${pathseq_path}/${each_sample}.output.pathseq.bam \
${pathseq_path}/${each_sample}.output.pathseq.csv \
${out_path}/${each_sample}.visium.raw_matrix.readname \
${out_path}/${each_sample}.visium.raw_matrix.unmap_cbub.bam \
${out_path}/${each_sample}.visium.raw_matrix.unmap_cbub.fasta \
${out_path}/${each_sample}.visium.raw_matrix.list \
${out_path}/${each_sample}.visium.raw.raw_matrix.readnamepath \
${out_path}/${each_sample}.visium.raw_matrix.genus.cell \
${out_path}/${each_sample}.visium.raw_matrix.genus.csv \
${out_path}/${each_sample}.visium.raw_matrix.validate.csv`
But the resulting document is inconsistent with the literature.The CRC_16.visium.raw_matrix.validate.csv file has 145518 lines recorded in the literature, but only 75129 lines were recorded in my results. 
Total UMI is 40402 in my result, and the literature is 84004. Total reads is 340883 in my result, and the literature is 795040. 
example: 
Genus,Number_of_Cells,Number_of_UMI,Number_of_reads
Fusobacterium,644,16075,100735

**Comment by hanruiw** [comment]
Hi, thanks for your reply, would you mind also share the printed out information from UMIannotator.py?
Hanrui

**Comment by hanruiw** [comment]
Dear Jianrong,

The size of our databases are exactly the same. I reran the pipeline and get the same results as before (total number of reads in PathSeq bam file is 6,279,844), while we have the same number of reads from Cellranger bam file (174,436,315).

Hanrui

**Comment by jr-ran** [comment]
Dear  Hanrui，
Thanks for your replay. May I ask if it is convenient to share the command for rerun pathseq？

**Comment by hanruiw** [comment]
`gatk --java-options "-Xmx750g" PathSeqPipelineSpark \
    --input ${file} \
    --filter-bwa-image ${pathseqdb}/pathseq_host.fa.img \
    --kmer-file ${pathseqdb}/pathseq_host.bfi \
    --min-clipped-read-length 60 \
    --microbe-fasta ${pathseqdb}/pathseq_microbe.fa \
    --microbe-bwa-image ${pathseqdb}/pathseq_microbe.fa.img \
    --taxonomy-file ${pathseqdb}/pathseq_taxonomy.db \
    --output ${outpath}/${samplename}.pathseq.complete.bam \
    --scores-output ${outpath}/${samplename}.pathseq.complete.csv \
    --is-host-aligned false \
    --filter-duplicates false \
    --min-score-identity .7`

**Comment by hanruiw** [comment]
Dear Jianrong,

As we discussed in the email, this issue was caused by missing parameters of --filter-duplicates false and --min-score-identity .7 when running PathSeq. Since it is solved, I'm going to close issue, but please let me know if you have any other questions!

Best regards,
Hanrui
