### ISSUE TITLE
Doubts about the SRA ID

### ISSUE THREAD

**Issue by februaryfang** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#11]
Dear Hanrui,
I would like to download the SRA data and test the codes. For each part of the code, I only need data from 2 samples. Can you recommend which SRA to download to me?
Currently, I have downloaded Fastq from "https://fh-pi-bullman-s-eco-public.s3.us-west-2.amazonaws.com/DataTransfer/Galeano_Nino_et_al_visium_scans/CRC_OSCC_visium_fastq.tar.gz" for part1. 

![image](https://github.com/FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022/assets/13863155/02725af6-46a3-47e9-bb61-96a1f0b438d7)
![image](https://github.com/FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022/assets/13863155/197affd6-9b18-4727-bfaa-feb2d39e4bfe)

And I will select the SRA data in the above figure for part 2. Is the SRA ID I have selected correct? Perhaps you can give me a clearer choice.

Best wish,
Fang

**Comment by hanruiw** [comment]
Dear Fang,

For questions regarding SRA, Would you mind send an email to Jorge, who is the first author of this paper? Please let me know if you need anything else!

Best regards,
Hanrui

**Comment by februaryfang** [comment]
How can I contact Jorge?

**Comment by februaryfang** [comment]
And I think there is a lack of data named "1_OSCC_11_GEX_S1_L002_I1_001".

**Comment by hanruiw** [comment]
jgaleano[a]fredhutch[dot]org
