### ISSUE TITLE
Visium QC filtering - Mitochondrial content

### ISSUE THREAD

**Issue by cathalgking** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#14]
Hi. I would just like to check what QC filtering steps were undergone for the 10x Visium samples? Was it just the filtering from space ranger? I am specifically interested in the metric '% mitochondrial content' and what parameter was used (if any)?

**Comment by hanruiw** [comment]
Hi,

Thanks for your interest in our paper! In the visium analysis, we used `tissue_sample <- subset(tissue_sample, subset = nCount_Spatial > 3 & nFeature_Spatial > 3)` for QC, and % mitochondrial content was not used in QC step.

Best,
Hanrui
