### ISSUE TITLE
Sample name in `headneck_gex_16s_mix_dedup.csv`

### ISSUE THREAD

**Issue by tmaruy** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#17]
Dear Hanrui, @hanruiw 

I am trying to reanalyze INVADEseq data of OSCC samples for my project. 
I tried to use bacterial UMI count in `headneck_gex_16s_mix_dedup.csv` but could not understand correspondence between samples and barcodes. 

By parsing the barcode names (e.g., sample_9218_T_AAAGTAGGTACCGGCT-1), I found the following seven prefixes. 
I suppose these prefixes represent seven donors in the paper (from OSCC_11 to OSCC_17) but could not find correspondence.

<html>
<body>

 prefix | number of barcodes    
-- | -- 
 sample_9218_T | 267 
 sample_9236_T | 1215  
sample_9237_T | 1051 
 sample_9347 | 163 
 sample_9398 | 2688 
 sample_BM319435 | 307 
sample_BM320030 | 4976

</body>
</html>

Could you give us the information? 
Or could you upload Seurat object you used in your manuscript? It would be super helpful to reuse your data.

Thank you so much,
tmaruy

**Comment by hanruiw** [comment]
Dear tmaruy,

Thank you very much for your interest in our paper titled "Effect of the intratumoral microbiota on spatial and cellular heterogeneity in cancer". For questions regarding sample IDs, could you please contact Dr. Jorge Luis Galeano Niño at jgaleano[at]fredhutch.org?

Thank you,
Hanrui

**Comment by tmaruy** [comment]
Could you share the Seurat object?

**Comment by hanruiw** [comment]
Hi, the expression matrix is not uploaded, so the best way to obtain the Seurat object is to process the raw fastq files. Please let me know if you have any questions!

**Comment by tmaruy** [comment]
Okay. I tried to contact Dr. Galeano Nino two weeks ago but no response. Would it be okay to ask him from your side?

**Comment by hanruiw** [comment]
Hi Tmaruy,
Sorry for delayed response, we updated the bacteria count matrix csv file with OSCC IDs, please let us know if you need anything else!
Best regards,
Hanrui
