### ISSUE TITLE
error for gatk PathSeqPipelineSpark "java: bwa.c:329: bwa_mem2idx: Assertion `k == l_mem' failed."

### ISSUE THREAD

**Issue by leogg738** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#18]
When I run this code
gatk --java-options "-Xmx150g" PathSeqPipelineSpark \
    --input endometriosis.bam \
    --filter-bwa-image pathseq_host.fa.img \
    --kmer-file pathseq_host.bfi \
    --min-clipped-read-length 60 \
    --microbe-fasta pathseq_microbe.fa \
    --microbe-bwa-image pathseq_microbe.fa.img \
    --taxonomy-file pathseq_taxonomy.db \
    --output endometriosis.pathseq.complete.bam \
    --scores-output endometriosis.pathseq.complete.csv \
    --is-host-aligned false \
    --filter-duplicates false \
    --min-score-identity .7

The following error message will appear：
**java: bwa.c:329: bwa_mem2idx: Assertion `k == l_mem' failed.**
Due to the log is too long, I can't paste all.

I don't know what caused this, and no one has raised similar questions. Please help me.

**Comment by hanruiw** [comment]
Dear leogg738,

Thank you for your interest in our paper, we have never seen this error before in our analysis, I would recommend you ask GATK team for help. Good luck with your analysis!

Best regards,
Hanrui
