### ISSUE TITLE
GATK pathseq

### ISSUE THREAD

**Issue by zhangshuyue1** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#4]
hello，when I run the GATK pathseq,how can I get all microbial reference fasta?

**Comment by hanruiw** [comment]
Hi, I would suggest you to check out the PathSeq documentations and tutorials for any questions regarding PathSeq: https://gatk.broadinstitute.org/hc/en-us/articles/360035889911--How-to-Run-the-Pathseq-pipeline
Good luck with your analysis!
