### ISSUE TITLE
GATK pathseq

### ISSUE THREAD

**Issue by zhangshuyue1** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#5]
Excuse me, can fasta of different bacteria be entered into BwaMemIndexImageCreator or PathSeqBuildReferenceTaxonomy together? Or one by one?

**Comment by hanruiw** [comment]
Hi, our pipeline didn't include the analysis of FASTA file. I would suggest to check out PathSeq documentations.
