### ISSUE TITLE
Availability of Seurat objs

### ISSUE THREAD

**Issue by MathiniVaikunthan** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#6]
Is the best way of obtaining the Seurat objs for the 0, 100, 500 MOI experiment in HCT116 to download all of the separate sequencing runs and go through the cell_culture_Seurat.r pipeline or is the output gene expression object stored somewhere? Thank you

**Comment by hanruiw** [comment]
Hi, the expression matrix is not uploaded, so the best way to obtain the R object is to process the raw fastq files. Please let me know if you have any questions!
