### ISSUE TITLE
Running pipeline for non-Visium data 

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#7]
Hi,
I am trying to use your pipeline for my  project, I have spatial data from breast cancer derived from a mouse model.
the data are not Visium but Slide-seq like.
I am using the full bam file of the sample 
So I want to ask you If I need to modify the UMI_annitator.py script somehow ?

My bam file looks like this, so the UB for me is MI and I already edit the script for it. 
But I am not python expert , do you think there is something else I need to change ?

![image](https://user-images.githubusercontent.com/48715846/219048040-4a2975ca-cf7d-4460-a2aa-dd488e70595d.png)
![image](https://user-images.githubusercontent.com/48715846/219048224-4db41756-97dc-460b-8c1f-d2bd5ef7528b.png)
![image](https://user-images.githubusercontent.com/48715846/219048493-ebce614f-4d49-4d56-a279-03b12e52ea58.png)

ALso I wanted to ask you what's the content of each column  in the readpath file, beacuse there are non headers  
![image](https://user-images.githubusercontent.com/48715846/219056230-0bb1b95b-9833-4395-a855-1c3a0cb95e70.png)

Thanks in advance,
Anna

**Comment by hanruiw** [comment]
Hi, Thank you for the questions, based on my understanding, the structure of your bam file is very similar to 10x Visium bam file. However, we have not assessed data from Slide-seq so I am sorry to say that I can't give you specific advice for that type of data. I wish you good luck with your analysis!

**Comment by AnnaAntonatouPap** [comment]
Thank you for the reply! Could you give me a hint about my second question, the headers in the readpath file?
so 1st column is the sequence, 2nd the barcode i guess  what about the 3nd and 5th?

**Comment by hanruiw** [comment]
Hi, The idea for the readnamepath file is to extract read-level information from Cellranger bam file and PathSeq bam file, the first column is read name, the second column is CB (corrected barcode), the third column is UB (corrected UMI), the forth column is YP from Pathseq bam (genus level and species level taxa id), the fifth column is mapping quality, and the sixth is the genus level annotation (based on YP). Good luck with your analysis and please let us know if you have any other questions!
