### ISSUE TITLE
Running for Part2. 10X single cell data

### ISSUE THREAD

**Issue by ChoiJi-Hye** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#8]
Hi,.
I have 3' 10x chromium 5' 10x chromium, 3' CITE-seq, 5' CITE-seq data.
Is there any problem with using the tool on my data or should I change the options in this scripts?

I would appreciate your help.

**Comment by hanruiw** [comment]
Hi, Thank you for the questions, we have not assessed data from 3' 10x chromium or CITE-seq, so I am sorry to say that I can't give you specific advice for that type of data. I wish you good luck with your analysis!
