### ISSUE TITLE
Requestion about Coordinate Information

### ISSUE THREAD

**Issue by yunbokai** [FredHutch/Galeano-Nino-Bullman-Intratumoral-Microbiota_2022#9]
Hello author, thank you for your wonderful paper. I am not a microbiology researcher, and I am more interested in studying tumor information in 10X Visium data. However, it is challenging to do so without coordinate information. Would it be possible for you to provide coordinate information?

**Comment by hanruiw** [comment]
Dear Bokai,
Thank you for expressing interest in our paper. We appreciate your enthusiasm and are glad to help with your inquiries.
Unfortunately, our project did not involve direct analysis of coordinate data, and we are not well-versed in that particular area. We have already shared all the information and resources we possess regarding Visium datasets. If you haven't already, we recommend checking the output from Space Ranger, which may contain the information you are seeking.
Please feel free to reach out if you have any further questions or need clarification on other aspects of our research. We wish you the best of luck with your analysis.
Best regards,
Hanrui
